name: CI
on: [pull_request]
jobs:
  hub-build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        id: tests
        run: ./scripts/tests.sh